export { default as Hero } from './Hero'
export { default as ValueProposition } from './ValueProposition'
export { default as HowItWorks } from './HowItWorks'
export { default as SocialProof } from './SocialProof'
export { default as Footer } from './Footer'
